INSERT INTO categories VALUES ("music", "Concerts &amp; Tour Dates");
INSERT INTO categories VALUES ("conference", "Conferences &amp; Tradeshows");
INSERT INTO categories VALUES ("comedy", "Comedy");
INSERT INTO categories VALUES ("learning_education", "Education");
INSERT INTO categories VALUES ("family_fun_kids", "Kids &amp; Family");
INSERT INTO categories VALUES ("festivals_parades", "Festivals");
INSERT INTO categories VALUES ("movies_film", "Film");
INSERT INTO categories VALUES ("food", "Food &amp; Wine");
INSERT INTO categories VALUES ("fundraisers", "Fundraising &amp; Charity");
INSERT INTO categories VALUES ("art", "Art Galleries &amp; Exhibits");
INSERT INTO categories VALUES ("support", "Health &amp; Wellness");
INSERT INTO categories VALUES ("holiday", "Holiday");
INSERT INTO categories VALUES ("books", "Literary &amp; Books");
INSERT INTO categories VALUES ("attractions", "Museums &amp; Attractions");
INSERT INTO categories VALUES ("community", "Neighborhood");
INSERT INTO categories VALUES ("business", "Business &amp; Networking");
INSERT INTO categories VALUES ("singles_social", "Nightlife &amp; Singles");
INSERT INTO categories VALUES ("schools_alumni", "University &amp; Alumni");
INSERT INTO categories VALUES ("clubs_associations", "Organizations &amp; Meetups");
INSERT INTO categories VALUES ("outdoors_recreation", "Outdoors &amp; Recreation");
INSERT INTO categories VALUES ("performing_arts", "Performing Arts");
INSERT INTO categories VALUES ("animals", "Pets");
INSERT INTO categories VALUES ("politics_activism", "Politics &amp; Activism");
INSERT INTO categories VALUES ("sales", "Sales &amp; Retail");
INSERT INTO categories VALUES ("science", "Science");
INSERT INTO categories VALUES ("religion_spirituality", "Religion &amp; Spirituality");
INSERT INTO categories VALUES ("sports", "Sports");
INSERT INTO categories VALUES ("technology", "Technology");
INSERT INTO categories VALUES ("other", "Other &amp; Miscellaneous");
